### ISSUE TITLE
App with target SDK 31+ crashes on Android 12+

### ISSUE THREAD

**Issue by peter-nilsson-scotts** [adobe/flutter_acpplaces_monitor#8]
### Expected Behaviour
App does not crash when starting location monitoring.

### Actual Behaviour
App crashes when starting location monitoring.

### Reproduce Scenario (including but not limited to)
Start location monitoring in build targeting SDK 31+ on Android 12+ device.

Google are now requiring all apps to target at least SDK 31.
`places-monitor-android` does not support SDK 31+, because it doesn't use the correct flags for pending intents.

#### Steps to Reproduce
- Build Android app with target SDK 31+
- Call `FlutterACPPlacesMonitor.start()` on Android 12+ device.

#### Platform and Version
Flutter 3.3.9, flutter_acpplaces_monitor 2.0.1, Android 12

#### Sample Code that illustrates the problem
`FlutterACPPlacesMonitor.start()`

#### Logs taken while reproducing problem
```
E/AndroidRuntime(13768): java.lang.IllegalArgumentException: <redacted>: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
E/AndroidRuntime(13768): Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
E/AndroidRuntime(13768):        at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
E/AndroidRuntime(13768):        at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:645)
E/AndroidRuntime(13768):        at android.app.PendingIntent.getBroadcast(PendingIntent.java:632)
E/AndroidRuntime(13768):        at com.adobe.marketing.mobile.PlacesLocationManager.getPendingIntent(PlacesLocationManager.java:375)
E/AndroidRuntime(13768):        at com.adobe.marketing.mobile.PlacesLocationManager.access$100(PlacesLocationManager.java:45)
E/AndroidRuntime(13768):        at com.adobe.marketing.mobile.PlacesLocationManager$1.onSuccess(PlacesLocationManager.java:139)
E/AndroidRuntime(13768):        at com.adobe.marketing.mobile.PlacesLocationManager$1.onSuccess(PlacesLocationManager.java:127)
E/AndroidRuntime(13768):        at com.google.android.gms.tasks.zzm.run(com.google.android.gms:play-services-tasks@@18.0.2:1)
E/AndroidRuntime(13768):        at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime(13768):        at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(13768):        at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime(13768):        at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime(13768):        at android.app.ActivityThread.main(ActivityThread.java:7839)
E/AndroidRuntime(13768):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(13768):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime(13768):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

**Comment by Joseph-Nathan** [comment]
??

**Comment by cacheung** [comment]
Places monitor is no longer supported, it is deprecated in August 2021.

**Comment by peter-nilsson-scotts** [comment]
@cacheung Yes, I know. I had to create my own fork of it to make it work. Why are you using it in this package, and why is there no mention of that in the documentation for this package?

**Comment by cacheung** [comment]
@peter-nilsson-scotts Thanks for the feedback.  We added the deprecation message in the readme.

Thanks,
Calise

**Comment by peter-nilsson-scotts** [comment]
@cacheung Thanks. Don't forget to update https://pub.dev/packages/flutter_acpplaces_monitor as well. :-)

**Comment by cacheung** [comment]
We won't be able to update the readme there without a release. We marked the package DISCOUNTIUED.   

Thanks,
Calise
